// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVmZoh-0_S207rcaf5vmu1vPSZ7pAidY',
    appId: '1:834334172185:web:76a3e1ccbe6d0ca95a7688',
    messagingSenderId: '834334172185',
    projectId: 'moneyscope-15133',
    authDomain: 'moneyscope-15133.firebaseapp.com',
    storageBucket: 'moneyscope-15133.firebasestorage.app',
    measurementId: 'G-CVC00J7ZM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQPj-bOpDvhsN1RKp-yquZpiwd184BzlY',
    appId: '1:834334172185:android:90132cd1d07bfef75a7688',
    messagingSenderId: '834334172185',
    projectId: 'moneyscope-15133',
    storageBucket: 'moneyscope-15133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRsk6TwokcMcfJSZ_kzl4mwsdKl1TWfQ',
    appId: '1:834334172185:ios:6354ccecb251142d5a7688',
    messagingSenderId: '834334172185',
    projectId: 'moneyscope-15133',
    storageBucket: 'moneyscope-15133.firebasestorage.app',
    iosBundleId: 'com.MoneyScope.WV86Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRsk6TwokcMcfJSZ_kzl4mwsdKl1TWfQ',
    appId: '1:834334172185:ios:c454975f71df1fbb5a7688',
    messagingSenderId: '834334172185',
    projectId: 'moneyscope-15133',
    storageBucket: 'moneyscope-15133.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZVmZoh-0_S207rcaf5vmu1vPSZ7pAidY',
    appId: '1:834334172185:web:fd152d1a52e2e70b5a7688',
    messagingSenderId: '834334172185',
    projectId: 'moneyscope-15133',
    authDomain: 'moneyscope-15133.firebaseapp.com',
    storageBucket: 'moneyscope-15133.firebasestorage.app',
    measurementId: 'G-J1L9D2M42H',
  );
}
